name: Up2DateRT
on:
  workflow_dispatch:
  schedule:
    - cron: "45 4 31 12 *"

jobs:
  rt:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: cupglassDEV/idholidays
          ref: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          git pull
          npm install
          node Up2Date.js
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "U2Dbot - Changed the 'preferredEdition' for about.json"
          git push

